export type Team = {
  id: string;
  name: string;
  nameEn: string;
  division: string;
  divisionEn: string;
  city: string;
  cityEn: string;
  stadium: string;
  stadiumEn: string;
};

export const TEAMS: Record<string, Team[]> = {
  KBO: [
    {
      id: "LG",
      name: "LG 트윈스",
      nameEn: "LG Twins",
      division: "KBO",
      divisionEn: "KBO",
      city: "서울",
      cityEn: "Seoul",
      stadium: "서울종합운동장 야구장 (잠실)",
      stadiumEn: "Jamsil Baseball Stadium",
    },
    {
      id: "DOOSAN",
      name: "두산 베어스",
      nameEn: "Doosan Bears",
      division: "KBO",
      divisionEn: "KBO",
      city: "서울",
      cityEn: "Seoul",
      stadium: "서울종합운동장 야구장 (잠실)",
      stadiumEn: "Jamsil Baseball Stadium",
    },
    {
      id: "KIWOOM",
      name: "키움 히어로즈",
      nameEn: "Kiwoom Heroes",
      division: "KBO",
      divisionEn: "KBO",
      city: "서울",
      cityEn: "Seoul",
      stadium: "고척 스카이돔",
      stadiumEn: "Gocheok Sky Dome",
    },
    {
      id: "SSG",
      name: "SSG 랜더스",
      nameEn: "SSG Landers",
      division: "KBO",
      divisionEn: "KBO",
      city: "인천",
      cityEn: "Incheon",
      stadium: "인천 SSG 랜더스필드",
      stadiumEn: "Incheon SSG Landers Field",
    },
    {
      id: "KT",
      name: "kt wiz",
      nameEn: "KT Wiz",
      division: "KBO",
      divisionEn: "KBO",
      city: "수원",
      cityEn: "Suwon",
      stadium: "수원 케이티 위즈 파크",
      stadiumEn: "Suwon KT Wiz Park",
    },
    {
      id: "KIA",
      name: "KIA 타이거즈",
      nameEn: "KIA Tigers",
      division: "KBO",
      divisionEn: "KBO",
      city: "광주",
      cityEn: "Gwangju",
      stadium: "광주-기아 챔피언스 필드",
      stadiumEn: "Gwangju-Kia Champions Field",
    },
    {
      id: "SAMSUNG",
      name: "삼성 라이온즈",
      nameEn: "Samsung Lions",
      division: "KBO",
      divisionEn: "KBO",
      city: "대구",
      cityEn: "Daegu",
      stadium: "대구 삼성 라이온즈 파크",
      stadiumEn: "Daegu Samsung Lions Park",
    },
    {
      id: "LOTTE",
      name: "롯데 자이언츠",
      nameEn: "Lotte Giants",
      division: "KBO",
      divisionEn: "KBO",
      city: "부산",
      cityEn: "Busan",
      stadium: "사직 야구장",
      stadiumEn: "Sajik Baseball Stadium",
    },
    {
      id: "HANWHA",
      name: "한화 이글스",
      nameEn: "Hanwha Eagles",
      division: "KBO",
      divisionEn: "KBO",
      city: "대전",
      cityEn: "Daejeon",
      stadium: "한화생명 이글스파크 (대전 베이스볼 드림파크)",
      stadiumEn: "Hanwha Life Eagles Park (Daejeon Baseball Dream Park)",
    },
    {
      id: "NC",
      name: "NC 다이노스",
      nameEn: "NC Dinos",
      division: "KBO",
      divisionEn: "KBO",
      city: "창원",
      cityEn: "Changwon",
      stadium: "창원 NC 파크",
      stadiumEn: "Changwon NC Park",
    },
  ],
  NBA: [
    {
      id: "BOS",
      name: "보스턴 셀틱스",
      nameEn: "Boston Celtics",
      division: "애틀랜틱",
      divisionEn: "Atlantic",
      city: "보스턴",
      cityEn: "Boston",
      stadium: "TD 가든",
      stadiumEn: "TD Garden",
    },
    {
      id: "BKN",
      name: "브루클린 네츠",
      nameEn: "Brooklyn Nets",
      division: "애틀랜틱",
      divisionEn: "Atlantic",
      city: "뉴욕 (브루클린)",
      cityEn: "New York (Brooklyn)",
      stadium: "바클레이스 센터",
      stadiumEn: "Barclays Center",
    },
    {
      id: "NYK",
      name: "뉴욕 닉스",
      nameEn: "New York Knicks",
      division: "애틀랜틱",
      divisionEn: "Atlantic",
      city: "뉴욕 (맨해튼)",
      cityEn: "New York (Manhattan)",
      stadium: "매디슨 스퀘어 가든",
      stadiumEn: "Madison Square Garden",
    },
    {
      id: "PHI",
      name: "필라델피아 세븐티식서스",
      nameEn: "Philadelphia 76ers",
      division: "애틀랜틱",
      divisionEn: "Atlantic",
      city: "필라델피아",
      cityEn: "Philadelphia",
      stadium: "웰스 파고 센터",
      stadiumEn: "Wells Fargo Center",
    },
    {
      id: "TOR",
      name: "토론토 랩터스",
      nameEn: "Toronto Raptors",
      division: "애틀랜틱",
      divisionEn: "Atlantic",
      city: "토론토",
      cityEn: "Toronto",
      stadium: "스코샤뱅크 아레나",
      stadiumEn: "Scotiabank Arena",
    },
    {
      id: "CHI",
      name: "시카고 불스",
      nameEn: "Chicago Bulls",
      division: "센트럴",
      divisionEn: "Central",
      city: "시카고",
      cityEn: "Chicago",
      stadium: "유나이티드 센터",
      stadiumEn: "United Center",
    },
    {
      id: "CLE",
      name: "클리블랜드 캐벌리어스",
      nameEn: "Cleveland Cavaliers",
      division: "센트럴",
      divisionEn: "Central",
      city: "클리블랜드",
      cityEn: "Cleveland",
      stadium: "로켓 모기지 필드하우스",
      stadiumEn: "Rocket Mortgage FieldHouse",
    },
    {
      id: "DET",
      name: "디트로이트 피스톤스",
      nameEn: "Detroit Pistons",
      division: "센트럴",
      divisionEn: "Central",
      city: "디트로이트",
      cityEn: "Detroit",
      stadium: "리틀 시저스 아레나",
      stadiumEn: "Little Caesars Arena",
    },
    {
      id: "IND",
      name: "인디애나 페이서스",
      nameEn: "Indiana Pacers",
      division: "센트럴",
      divisionEn: "Central",
      city: "인디애나폴리스",
      cityEn: "Indianapolis",
      stadium: "게인브리지 필드하우스",
      stadiumEn: "Gainbridge Fieldhouse",
    },
    {
      id: "MIL",
      name: "밀워키 벅스",
      nameEn: "Milwaukee Bucks",
      division: "센트럴",
      divisionEn: "Central",
      city: "밀워키",
      cityEn: "Milwaukee",
      stadium: "파이서브 포럼",
      stadiumEn: "Fiserv Forum",
    },
    {
      id: "ATL",
      name: "애틀랜타 호크스",
      nameEn: "Atlanta Hawks",
      division: "사우스이스트",
      divisionEn: "Southeast",
      city: "애틀랜타",
      cityEn: "Atlanta",
      stadium: "스테이트 팜 아레나",
      stadiumEn: "State Farm Arena",
    },
    {
      id: "CHA",
      name: "샬럿 호네츠",
      nameEn: "Charlotte Hornets",
      division: "사우스이스트",
      divisionEn: "Southeast",
      city: "샬럿",
      cityEn: "Charlotte",
      stadium: "스펙트럼 센터",
      stadiumEn: "Spectrum Center",
    },
    {
      id: "MIA",
      name: "마이애미 히트",
      nameEn: "Miami Heat",
      division: "사우스이스트",
      divisionEn: "Southeast",
      city: "마이애미",
      cityEn: "Miami",
      stadium: "카세야 센터",
      stadiumEn: "Kaseya Center",
    },
    {
      id: "ORL",
      name: "올랜도 매직",
      nameEn: "Orlando Magic",
      division: "사우스이스트",
      divisionEn: "Southeast",
      city: "올랜도",
      cityEn: "Orlando",
      stadium: "기아 센터",
      stadiumEn: "Kia Center",
    },
    {
      id: "WAS",
      name: "워싱턴 위저즈",
      nameEn: "Washington Wizards",
      division: "사우스이스트",
      divisionEn: "Southeast",
      city: "워싱턴 D.C.",
      cityEn: "Washington D.C.",
      stadium: "캐피털 원 아레나",
      stadiumEn: "Capital One Arena",
    },
    {
      id: "DEN",
      name: "덴버 너기츠",
      nameEn: "Denver Nuggets",
      division: "노스웨스트",
      divisionEn: "Northwest",
      city: "덴버",
      cityEn: "Denver",
      stadium: "볼 아레나",
      stadiumEn: "Ball Arena",
    },
    {
      id: "MIN",
      name: "미네소타 팀버울브스",
      nameEn: "Minnesota Timberwolves",
      division: "노스웨스트",
      divisionEn: "Northwest",
      city: "미니애폴리스",
      cityEn: "Minneapolis",
      stadium: "타깃 센터",
      stadiumEn: "Target Center",
    },
    {
      id: "OKC",
      name: "오클라호마시티 썬더",
      nameEn: "Oklahoma City Thunder",
      division: "노스웨스트",
      divisionEn: "Northwest",
      city: "오클라호마시티",
      cityEn: "Oklahoma City",
      stadium: "페이컴 센터",
      stadiumEn: "Paycom Center",
    },
    {
      id: "POR",
      name: "포틀랜드 트레일블레이저스",
      nameEn: "Portland Trail Blazers",
      division: "노스웨스트",
      divisionEn: "Northwest",
      city: "포틀랜드",
      cityEn: "Portland",
      stadium: "모다 센터",
      stadiumEn: "Moda Center",
    },
    {
      id: "UTA",
      name: "유타 재즈",
      nameEn: "Utah Jazz",
      division: "노스웨스트",
      divisionEn: "Northwest",
      city: "솔트레이크시티",
      cityEn: "Salt Lake City",
      stadium: "델타 센터",
      stadiumEn: "Delta Center",
    },
    {
      id: "GSW",
      name: "골든스테이트 워리어스",
      nameEn: "Golden State Warriors",
      division: "퍼시픽",
      divisionEn: "Pacific",
      city: "샌프란시스코",
      cityEn: "San Francisco",
      stadium: "체이스 센터",
      stadiumEn: "Chase Center",
    },
    {
      id: "LAC",
      name: "LA 클리퍼스",
      nameEn: "LA Clippers",
      division: "퍼시픽",
      divisionEn: "Pacific",
      city: "잉글우드",
      cityEn: "Inglewood",
      stadium: "인튜이트 돔",
      stadiumEn: "Intuit Dome",
    },
    {
      id: "LAL",
      name: "LA 레이커스",
      nameEn: "Los Angeles Lakers",
      division: "퍼시픽",
      divisionEn: "Pacific",
      city: "로스앤젤레스",
      cityEn: "Los Angeles",
      stadium: "크립토닷컴 아레나",
      stadiumEn: "Crypto.com Arena",
    },
    {
      id: "PHX",
      name: "피닉스 선즈",
      nameEn: "Phoenix Suns",
      division: "퍼시픽",
      divisionEn: "Pacific",
      city: "피닉스",
      cityEn: "Phoenix",
      stadium: "풋프린트 센터",
      stadiumEn: "Footprint Center",
    },
    {
      id: "SAC",
      name: "새크라멘토 킹스",
      nameEn: "Sacramento Kings",
      division: "퍼시픽",
      divisionEn: "Pacific",
      city: "새크라멘토",
      cityEn: "Sacramento",
      stadium: "골든 1 센터",
      stadiumEn: "Golden 1 Center",
    },
    {
      id: "DAL",
      name: "댈러스 매버릭스",
      nameEn: "Dallas Mavericks",
      division: "사우스웨스트",
      divisionEn: "Southwest",
      city: "댈러스",
      cityEn: "Dallas",
      stadium: "아메리칸 에어라인스 센터",
      stadiumEn: "American Airlines Center",
    },
    {
      id: "HOU",
      name: "휴스턴 로키츠",
      nameEn: "Houston Rockets",
      division: "사우스웨스트",
      divisionEn: "Southwest",
      city: "휴스턴",
      cityEn: "Houston",
      stadium: "도요타 센터",
      stadiumEn: "Toyota Center",
    },
    {
      id: "MEM",
      name: "멤피스 그리즐리스",
      nameEn: "Memphis Grizzlies",
      division: "사우스웨스트",
      divisionEn: "Southwest",
      city: "멤피스",
      cityEn: "Memphis",
      stadium: "페덱스 포럼",
      stadiumEn: "FedExForum",
    },
    {
      id: "NOP",
      name: "뉴올리언스 펠리컨스",
      nameEn: "New Orleans Pelicans",
      division: "사우스웨스트",
      divisionEn: "Southwest",
      city: "뉴올리언스",
      cityEn: "New Orleans",
      stadium: "스무디킹 센터",
      stadiumEn: "Smoothie King Center",
    },
    {
      id: "SAS",
      name: "샌안토니오 스퍼스",
      nameEn: "San Antonio Spurs",
      division: "사우스웨스트",
      divisionEn: "Southwest",
      city: "샌안토니오",
      cityEn: "San Antonio",
      stadium: "프로스트 뱅크 센터",
      stadiumEn: "Frost Bank Center",
    },
  ],
  MLB: [
    {
      id: "BAL",
      name: "볼티모어 오리올스",
      nameEn: "Baltimore Orioles",
      division: "아메리칸 동부",
      divisionEn: "AL East",
      city: "볼티모어",
      cityEn: "Baltimore",
      stadium: "오리올 파크 앳 캠든 야즈",
      stadiumEn: "Oriole Park at Camden Yards",
    },
    {
      id: "BOS",
      name: "보스턴 레드삭스",
      nameEn: "Boston Red Sox",
      division: "아메리칸 동부",
      divisionEn: "AL East",
      city: "보스턴",
      cityEn: "Boston",
      stadium: "펜웨이 파크",
      stadiumEn: "Fenway Park",
    },
    {
      id: "NYY",
      name: "뉴욕 양키스",
      nameEn: "New York Yankees",
      division: "아메리칸 동부",
      divisionEn: "AL East",
      city: "뉴욕 (브롱크스)",
      cityEn: "New York (Bronx)",
      stadium: "양키 스타디움",
      stadiumEn: "Yankee Stadium",
    },
    {
      id: "TBR",
      name: "탬파베이 레이스",
      nameEn: "Tampa Bay Rays",
      division: "아메리칸 동부",
      divisionEn: "AL East",
      city: "세인트피터즈버그",
      cityEn: "St. Petersburg",
      stadium: "트로피카나 필드",
      stadiumEn: "Tropicana Field",
    },
    {
      id: "TOR",
      name: "토론토 블루제이스",
      nameEn: "Toronto Blue Jays",
      division: "아메리칸 동부",
      divisionEn: "AL East",
      city: "토론토",
      cityEn: "Toronto",
      stadium: "로저스 센터",
      stadiumEn: "Rogers Centre",
    },
    {
      id: "CWS",
      name: "시카고 화이트삭스",
      nameEn: "Chicago White Sox",
      division: "아메리칸 중부",
      divisionEn: "AL Central",
      city: "시카고",
      cityEn: "Chicago",
      stadium: "개런티드 레이트 필드",
      stadiumEn: "Guaranteed Rate Field",
    },
    {
      id: "CLE",
      name: "클리블랜드 가디언스",
      nameEn: "Cleveland Guardians",
      division: "아메리칸 중부",
      divisionEn: "AL Central",
      city: "클리블랜드",
      cityEn: "Cleveland",
      stadium: "프로그레시브 필드",
      stadiumEn: "Progressive Field",
    },
    {
      id: "DET",
      name: "디트로이트 타이거스",
      nameEn: "Detroit Tigers",
      division: "아메리칸 중부",
      divisionEn: "AL Central",
      city: "디트로이트",
      cityEn: "Detroit",
      stadium: "코메리카 파크",
      stadiumEn: "Comerica Park",
    },
    {
      id: "KCR",
      name: "캔자스시티 로열스",
      nameEn: "Kansas City Royals",
      division: "아메리칸 중부",
      divisionEn: "AL Central",
      city: "캔자스시티",
      cityEn: "Kansas City",
      stadium: "코프먼 스타디움",
      stadiumEn: "Kauffman Stadium",
    },
    {
      id: "MIN",
      name: "미네소타 트윈스",
      nameEn: "Minnesota Twins",
      division: "아메리칸 중부",
      divisionEn: "AL Central",
      city: "미니애폴리스",
      cityEn: "Minneapolis",
      stadium: "타깃 필드",
      stadiumEn: "Target Field",
    },
    {
      id: "HOU",
      name: "휴스턴 애스트로스",
      nameEn: "Houston Astros",
      division: "아메리칸 서부",
      divisionEn: "AL West",
      city: "휴스턴",
      cityEn: "Houston",
      stadium: "다이킨 파크",
      stadiumEn: "Daikin Park",
    },
    {
      id: "LAA",
      name: "LA 에인절스",
      nameEn: "Los Angeles Angels",
      division: "아메리칸 서부",
      divisionEn: "AL West",
      city: "애너하임",
      cityEn: "Anaheim",
      stadium: "에인절 스타디움",
      stadiumEn: "Angel Stadium",
    },
    {
      id: "ATH",
      name: "애슬레틱스",
      nameEn: "Athletics",
      division: "아메리칸 서부",
      divisionEn: "AL West",
      city: "웨스트 새크라멘토 (임시)",
      cityEn: "West Sacramento (Temp)",
      stadium: "서터 헬스 파크",
      stadiumEn: "Sutter Health Park",
    },
    {
      id: "SEA",
      name: "시애틀 매리너스",
      nameEn: "Seattle Mariners",
      division: "아메리칸 서부",
      divisionEn: "AL West",
      city: "시애틀",
      cityEn: "Seattle",
      stadium: "T-모바일 파크",
      stadiumEn: "T-Mobile Park",
    },
    {
      id: "TEX",
      name: "텍사스 레인저스",
      nameEn: "Texas Rangers",
      division: "아메리칸 서부",
      divisionEn: "AL West",
      city: "알링턴",
      cityEn: "Arlington",
      stadium: "글로벌 라이프 필드",
      stadiumEn: "Globe Life Field",
    },
    {
      id: "ATL",
      name: "애틀랜타 브레이브스",
      nameEn: "Atlanta Braves",
      division: "내셔널 동부",
      divisionEn: "NL East",
      city: "애틀랜타",
      cityEn: "Atlanta",
      stadium: "트루이스트 파크",
      stadiumEn: "Truist Park",
    },
    {
      id: "MIA",
      name: "마이애미 말린스",
      nameEn: "Miami Marlins",
      division: "내셔널 동부",
      divisionEn: "NL East",
      city: "마이애미",
      cityEn: "Miami",
      stadium: "론디포 파크",
      stadiumEn: "LoanDepot Park",
    },
    {
      id: "NYM",
      name: "뉴욕 메츠",
      nameEn: "New York Mets",
      division: "내셔널 동부",
      divisionEn: "NL East",
      city: "뉴욕 (퀸스)",
      cityEn: "New York (Queens)",
      stadium: "시티 필드",
      stadiumEn: "Citi Field",
    },
    {
      id: "PHI",
      name: "필라델피아 필리스",
      nameEn: "Philadelphia Phillies",
      division: "내셔널 동부",
      divisionEn: "NL East",
      city: "필라델피아",
      cityEn: "Philadelphia",
      stadium: "시티즌스 뱅크 파크",
      stadiumEn: "Citizens Bank Park",
    },
    {
      id: "WSH",
      name: "워싱턴 내셔널스",
      nameEn: "Washington Nationals",
      division: "내셔널 동부",
      divisionEn: "NL East",
      city: "워싱턴 D.C.",
      cityEn: "Washington D.C.",
      stadium: "내셔널스 파크",
      stadiumEn: "Nationals Park",
    },
    {
      id: "CHC",
      name: "시카고 컵스",
      nameEn: "Chicago Cubs",
      division: "내셔널 중부",
      divisionEn: "NL Central",
      city: "시카고",
      cityEn: "Chicago",
      stadium: "리글리 필드",
      stadiumEn: "Wrigley Field",
    },
    {
      id: "CIN",
      name: "신시내티 레즈",
      nameEn: "Cincinnati Reds",
      division: "내셔널 중부",
      divisionEn: "NL Central",
      city: "신시내티",
      cityEn: "Cincinnati",
      stadium: "그레이트 아메리칸 볼 파크",
      stadiumEn: "Great American Ball Park",
    },
    {
      id: "MIL",
      name: "밀워키 브루어스",
      nameEn: "Milwaukee Brewers",
      division: "내셔널 중부",
      divisionEn: "NL Central",
      city: "밀워키",
      cityEn: "Milwaukee",
      stadium: "아메리칸 패밀리 필드",
      stadiumEn: "American Family Field",
    },
    {
      id: "PIT",
      name: "피츠버그 파이리츠",
      nameEn: "Pittsburgh Pirates",
      division: "내셔널 중부",
      divisionEn: "NL Central",
      city: "피츠버그",
      cityEn: "Pittsburgh",
      stadium: "PNC 파크",
      stadiumEn: "PNC Park",
    },
    {
      id: "STL",
      name: "세인트루이스 카디널스",
      nameEn: "St. Louis Cardinals",
      division: "내셔널 중부",
      divisionEn: "NL Central",
      city: "세인트루이스",
      cityEn: "St. Louis",
      stadium: "부시 스타디움",
      stadiumEn: "Busch Stadium",
    },
    {
      id: "ARI",
      name: "애리조나 다이아몬드백스",
      nameEn: "Arizona Diamondbacks",
      division: "내셔널 서부",
      divisionEn: "NL West",
      city: "피닉스",
      cityEn: "Phoenix",
      stadium: "체이스 필드",
      stadiumEn: "Chase Field",
    },
    {
      id: "COL",
      name: "콜로라도 로키스",
      nameEn: "Colorado Rockies",
      division: "내셔널 서부",
      divisionEn: "NL West",
      city: "덴버",
      cityEn: "Denver",
      stadium: "쿠어스 필드",
      stadiumEn: "Coors Field",
    },
    {
      id: "LAD",
      name: "LA 다저스",
      nameEn: "Los Angeles Dodgers",
      division: "내셔널 서부",
      divisionEn: "NL West",
      city: "로스앤젤레스",
      cityEn: "Los Angeles",
      stadium: "다저 스타디움",
      stadiumEn: "Dodger Stadium",
    },
    {
      id: "SDP",
      name: "샌디에이고 파드리스",
      nameEn: "San Diego Padres",
      division: "내셔널 서부",
      divisionEn: "NL West",
      city: "샌디에이고",
      cityEn: "San Diego",
      stadium: "펫코 파크",
      stadiumEn: "Petco Park",
    },
    {
      id: "SFG",
      name: "샌프란시스코 자이언츠",
      nameEn: "San Francisco Giants",
      division: "내셔널 서부",
      divisionEn: "NL West",
      city: "샌프란시스코",
      cityEn: "San Francisco",
      stadium: "오라클 파크",
      stadiumEn: "Oracle Park",
    },
  ],
  EPL: [
    {
      id: "ARS",
      name: "아스널",
      nameEn: "Arsenal",
      division: "런던",
      divisionEn: "London",
      city: "런던 (이즐링턴)",
      cityEn: "London (Islington)",
      stadium: "에미레이츠 스타디움",
      stadiumEn: "Emirates Stadium",
    },
    {
      id: "BRE",
      name: "브렌트포드",
      nameEn: "Brentford",
      division: "런던",
      divisionEn: "London",
      city: "런던 (하운즐로)",
      cityEn: "London (Hounslow)",
      stadium: "지테크 커뮤니티 스타디움",
      stadiumEn: "Gtech Community Stadium",
    },
    {
      id: "CHE",
      name: "첼시",
      nameEn: "Chelsea",
      division: "런던",
      divisionEn: "London",
      city: "런던 (풀럼)",
      cityEn: "London (Fulham)",
      stadium: "스탬퍼드 브리지",
      stadiumEn: "Stamford Bridge",
    },
    {
      id: "CRY",
      name: "크리스털 팰리스",
      nameEn: "Crystal Palace",
      division: "런던",
      divisionEn: "London",
      city: "런던 (크로이든)",
      cityEn: "London (Croydon)",
      stadium: "셀허스트 파크",
      stadiumEn: "Selhurst Park",
    },
    {
      id: "FUL",
      name: "풀럼",
      nameEn: "Fulham",
      division: "런던",
      divisionEn: "London",
      city: "런던 (풀럼)",
      cityEn: "London (Fulham)",
      stadium: "크레이븐 코티지",
      stadiumEn: "Craven Cottage",
    },
    {
      id: "TOT",
      name: "토트넘 홋스퍼",
      nameEn: "Tottenham Hotspur",
      division: "런던",
      divisionEn: "London",
      city: "런던 (해링게이)",
      cityEn: "London (Haringey)",
      stadium: "토트넘 홋스퍼 스타디움",
      stadiumEn: "Tottenham Hotspur Stadium",
    },
    {
      id: "WHU",
      name: "웨스트햄 유나이티드",
      nameEn: "West Ham United",
      division: "런던",
      divisionEn: "London",
      city: "런던 (뉴엄)",
      cityEn: "London (Newham)",
      stadium: "런던 스타디움",
      stadiumEn: "London Stadium",
    },
    {
      id: "LIV",
      name: "리버풀",
      nameEn: "Liverpool",
      division: "노스 웨스트",
      divisionEn: "North West",
      city: "리버풀",
      cityEn: "Liverpool",
      stadium: "안필드",
      stadiumEn: "Anfield",
    },
    {
      id: "EVE",
      name: "에버턴",
      nameEn: "Everton",
      division: "노스 웨스트",
      divisionEn: "North West",
      city: "리버풀",
      cityEn: "Liverpool",
      stadium: "구디슨 파크",
      stadiumEn: "Goodison Park",
    },
    {
      id: "MCI",
      name: "맨체스터 시티",
      nameEn: "Manchester City",
      division: "노스 웨스트",
      divisionEn: "North West",
      city: "맨체스터",
      cityEn: "Manchester",
      stadium: "에티하드 스타디움",
      stadiumEn: "Etihad Stadium",
    },
    {
      id: "MUN",
      name: "맨체스터 유나이티드",
      nameEn: "Manchester United",
      division: "노스 웨스트",
      divisionEn: "North West",
      city: "맨체스터 (트래퍼드)",
      cityEn: "Manchester (Trafford)",
      stadium: "올드 트래퍼드",
      stadiumEn: "Old Trafford",
    },
    {
      id: "NEW",
      name: "뉴캐슬 유나이티드",
      nameEn: "Newcastle United",
      division: "노스 이스트",
      divisionEn: "North East",
      city: "뉴캐슬어폰타인",
      cityEn: "Newcastle upon Tyne",
      stadium: "세인트 제임스 파크",
      stadiumEn: "St. James' Park",
    },
    {
      id: "AVL",
      name: "아스톤 빌라",
      nameEn: "Aston Villa",
      division: "웨스트 미들랜즈",
      divisionEn: "West Midlands",
      city: "버밍엄",
      cityEn: "Birmingham",
      stadium: "빌라 파크",
      stadiumEn: "Villa Park",
    },
    {
      id: "WOL",
      name: "울버햄튼 원더러스",
      nameEn: "Wolverhampton Wanderers",
      division: "웨스트 미들랜즈",
      divisionEn: "West Midlands",
      city: "울버햄튼",
      cityEn: "Wolverhampton",
      stadium: "몰리뉴 스타디움",
      stadiumEn: "Molineux Stadium",
    },
    {
      id: "LEI",
      name: "레스터 시티",
      nameEn: "Leicester City",
      division: "이스트 미들랜즈",
      divisionEn: "East Midlands",
      city: "레스터",
      cityEn: "Leicester",
      stadium: "킹 파워 스타디움",
      stadiumEn: "King Power Stadium",
    },
    {
      id: "NOT",
      name: "노팅엄 포레스트",
      nameEn: "Nottingham Forest",
      division: "이스트 미들랜즈",
      divisionEn: "East Midlands",
      city: "노팅엄 (웨스트 브리지퍼드)",
      cityEn: "Nottingham (West Bridgford)",
      stadium: "시티 그라운드",
      stadiumEn: "City Ground",
    },
    {
      id: "IPS",
      name: "입스위치 타운",
      nameEn: "Ipswich Town",
      division: "이스트",
      divisionEn: "East",
      city: "입스위치",
      cityEn: "Ipswich",
      stadium: "포트먼 로드",
      stadiumEn: "Portman Road",
    },
    {
      id: "BHA",
      name: "브라이턴 앤 호브 알비온",
      nameEn: "Brighton & Hove Albion",
      division: "사우스 이스트",
      divisionEn: "South East",
      city: "브라이턴",
      cityEn: "Brighton",
      stadium: "아메리칸 익스프레스 스타디움",
      stadiumEn: "American Express Stadium",
    },
    {
      id: "SOU",
      name: "사우샘프턴",
      nameEn: "Southampton",
      division: "사우스 이스트",
      divisionEn: "South East",
      city: "사우샘프턴",
      cityEn: "Southampton",
      stadium: "세인트 메리스 스타디움",
      stadiumEn: "St Mary's Stadium",
    },
    {
      id: "BOU",
      name: "본머스",
      nameEn: "AFC Bournemouth",
      division: "사우스 웨스트",
      divisionEn: "South West",
      city: "본머스",
      cityEn: "Bournemouth",
      stadium: "바이탈리티 스타디움",
      stadiumEn: "Vitality Stadium",
    },
  ],
  NHL: [
    {
      id: "BOS",
      name: "보스턴 브루인스",
      nameEn: "Boston Bruins",
      division: "애틀랜틱",
      divisionEn: "Atlantic",
      city: "보스턴",
      cityEn: "Boston",
      stadium: "TD 가든",
      stadiumEn: "TD Garden",
    },
    {
      id: "BUF",
      name: "버펄로 세이버스",
      nameEn: "Buffalo Sabres",
      division: "애틀랜틱",
      divisionEn: "Atlantic",
      city: "버펄로",
      cityEn: "Buffalo",
      stadium: "키뱅크 센터",
      stadiumEn: "KeyBank Center",
    },
    {
      id: "DET",
      name: "디트로이트 레드윙스",
      nameEn: "Detroit Red Wings",
      division: "애틀랜틱",
      divisionEn: "Atlantic",
      city: "디트로이트",
      cityEn: "Detroit",
      stadium: "리틀 시저스 아레나",
      stadiumEn: "Little Caesars Arena",
    },
    {
      id: "FLA",
      name: "플로리다 팬서스",
      nameEn: "Florida Panthers",
      division: "애틀랜틱",
      divisionEn: "Atlantic",
      city: "선라이즈 (마이애미)",
      cityEn: "Sunrise (Miami)",
      stadium: "아메란트 뱅크 아레나",
      stadiumEn: "Amerant Bank Arena",
    },
    {
      id: "MTL",
      name: "몬트리올 캐네디언스",
      nameEn: "Montreal Canadiens",
      division: "애틀랜틱",
      divisionEn: "Atlantic",
      city: "몬트리올",
      cityEn: "Montreal",
      stadium: "벨 센터",
      stadiumEn: "Bell Centre",
    },
    {
      id: "OTT",
      name: "오타와 세너터스",
      nameEn: "Ottawa Senators",
      division: "애틀랜틱",
      divisionEn: "Atlantic",
      city: "오타와",
      cityEn: "Ottawa",
      stadium: "캐내디언 타이어 센터",
      stadiumEn: "Canadian Tire Centre",
    },
    {
      id: "TBL",
      name: "탬파베이 라이트닝",
      nameEn: "Tampa Bay Lightning",
      division: "애틀랜틱",
      divisionEn: "Atlantic",
      city: "탬파",
      cityEn: "Tampa",
      stadium: "아말리 아레나",
      stadiumEn: "Amalie Arena",
    },
    {
      id: "TOR",
      name: "토론토 메이플 리프스",
      nameEn: "Toronto Maple Leafs",
      division: "애틀랜틱",
      divisionEn: "Atlantic",
      city: "토론토",
      cityEn: "Toronto",
      stadium: "스코샤뱅크 아레나",
      stadiumEn: "Scotiabank Arena",
    },
    {
      id: "CAR",
      name: "캐롤라이나 허리케인스",
      nameEn: "Carolina Hurricanes",
      division: "메트로폴리탄",
      divisionEn: "Metropolitan",
      city: "롤리",
      cityEn: "Raleigh",
      stadium: "레노버 센터",
      stadiumEn: "Lenovo Center",
    },
    {
      id: "CBJ",
      name: "콜럼버스 블루재키츠",
      nameEn: "Columbus Blue Jackets",
      division: "메트로폴리탄",
      divisionEn: "Metropolitan",
      city: "콜럼버스",
      cityEn: "Columbus",
      stadium: "네이션와이드 아레나",
      stadiumEn: "Nationwide Arena",
    },
    {
      id: "NJD",
      name: "뉴저지 데블스",
      nameEn: "New Jersey Devils",
      division: "메트로폴리탄",
      divisionEn: "Metropolitan",
      city: "뉴어크",
      cityEn: "Newark",
      stadium: "프루덴셜 센터",
      stadiumEn: "Prudential Center",
    },
    {
      id: "NYI",
      name: "뉴욕 아일런더스",
      nameEn: "New York Islanders",
      division: "메트로폴리탄",
      divisionEn: "Metropolitan",
      city: "엘먼트 (롱아일랜드)",
      cityEn: "Elmont (Long Island)",
      stadium: "UBS 아레나",
      stadiumEn: "UBS Arena",
    },
    {
      id: "NYR",
      name: "뉴욕 레인저스",
      nameEn: "New York Rangers",
      division: "메트로폴리탄",
      divisionEn: "Metropolitan",
      city: "뉴욕 (맨해튼)",
      cityEn: "New York (Manhattan)",
      stadium: "매디슨 스퀘어 가든",
      stadiumEn: "Madison Square Garden",
    },
    {
      id: "PHI",
      name: "필라델피아 플라이어스",
      nameEn: "Philadelphia Flyers",
      division: "메트로폴리탄",
      divisionEn: "Metropolitan",
      city: "필라델피아",
      cityEn: "Philadelphia",
      stadium: "웰스 파고 센터",
      stadiumEn: "Wells Fargo Center",
    },
    {
      id: "PIT",
      name: "피츠버그 펭귄스",
      nameEn: "Pittsburgh Penguins",
      division: "메트로폴리탄",
      divisionEn: "Metropolitan",
      city: "피츠버그",
      cityEn: "Pittsburgh",
      stadium: "PPG 페인츠 아레나",
      stadiumEn: "PPG Paints Arena",
    },
    {
      id: "WSH",
      name: "워싱턴 캐피털스",
      nameEn: "Washington Capitals",
      division: "메트로폴리탄",
      divisionEn: "Metropolitan",
      city: "워싱턴 D.C.",
      cityEn: "Washington D.C.",
      stadium: "캐피털 원 아레나",
      stadiumEn: "Capital One Arena",
    },
    {
      id: "CHI",
      name: "시카고 블랙호크스",
      nameEn: "Chicago Blackhawks",
      division: "센트럴",
      divisionEn: "Central",
      city: "시카고",
      cityEn: "Chicago",
      stadium: "유나이티드 센터",
      stadiumEn: "United Center",
    },
    {
      id: "COL",
      name: "콜로라도 애벌랜치",
      nameEn: "Colorado Avalanche",
      division: "센트럴",
      divisionEn: "Central",
      city: "덴버",
      cityEn: "Denver",
      stadium: "볼 아레나",
      stadiumEn: "Ball Arena",
    },
    {
      id: "DAL",
      name: "댈러스 스타스",
      nameEn: "Dallas Stars",
      division: "센트럴",
      divisionEn: "Central",
      city: "댈러스",
      cityEn: "Dallas",
      stadium: "아메리칸 에어라인스 센터",
      stadiumEn: "American Airlines Center",
    },
    {
      id: "MIN",
      name: "미네소타 와일드",
      nameEn: "Minnesota Wild",
      division: "센트럴",
      divisionEn: "Central",
      city: "세인트폴",
      cityEn: "Saint Paul",
      stadium: "엑셀 에너지 센터",
      stadiumEn: "Xcel Energy Center",
    },
    {
      id: "NSH",
      name: "내슈빌 프레데터스",
      nameEn: "Nashville Predators",
      division: "센트럴",
      divisionEn: "Central",
      city: "내슈빌",
      cityEn: "Nashville",
      stadium: "브리지스톤 아레나",
      stadiumEn: "Bridgestone Arena",
    },
    {
      id: "STL",
      name: "세인트루이스 블루스",
      nameEn: "St. Louis Blues",
      division: "센트럴",
      divisionEn: "Central",
      city: "세인트루이스",
      cityEn: "St. Louis",
      stadium: "엔터프라이즈 센터",
      stadiumEn: "Enterprise Center",
    },
    {
      id: "UTA",
      name: "유타 하키 클럽",
      nameEn: "Utah Hockey Club",
      division: "센트럴",
      divisionEn: "Central",
      city: "솔트레이크시티",
      cityEn: "Salt Lake City",
      stadium: "델타 센터",
      stadiumEn: "Delta Center",
    },
    {
      id: "WPG",
      name: "위니펙 제츠",
      nameEn: "Winnipeg Jets",
      division: "센트럴",
      divisionEn: "Central",
      city: "위니펙",
      cityEn: "Winnipeg",
      stadium: "캐나다 라이프 센터",
      stadiumEn: "Canada Life Centre",
    },
    {
      id: "ANA",
      name: "애너하임 덕스",
      nameEn: "Anaheim Ducks",
      division: "퍼시픽",
      divisionEn: "Pacific",
      city: "애너하임",
      cityEn: "Anaheim",
      stadium: "혼다 센터",
      stadiumEn: "Honda Center",
    },
    {
      id: "CGY",
      name: "캘거리 플레임스",
      nameEn: "Calgary Flames",
      division: "퍼시픽",
      divisionEn: "Pacific",
      city: "캘거리",
      cityEn: "Calgary",
      stadium: "스코샤뱅크 새들돔",
      stadiumEn: "Scotiabank Saddledome",
    },
    {
      id: "EDM",
      name: "에드먼턴 오일러스",
      nameEn: "Edmonton Oilers",
      division: "퍼시픽",
      divisionEn: "Pacific",
      city: "에드먼턴",
      cityEn: "Edmonton",
      stadium: "로저스 플레이스",
      stadiumEn: "Rogers Place",
    },
    {
      id: "LAK",
      name: "LA 킹스",
      nameEn: "Los Angeles Kings",
      division: "퍼시픽",
      divisionEn: "Pacific",
      city: "로스앤젤레스",
      cityEn: "Los Angeles",
      stadium: "크립토닷컴 아레나",
      stadiumEn: "Crypto.com Arena",
    },
    {
      id: "SJS",
      name: "산호세 샤크스",
      nameEn: "San Jose Sharks",
      division: "퍼시픽",
      divisionEn: "Pacific",
      city: "산호세",
      cityEn: "San Jose",
      stadium: "SAP 센터",
      stadiumEn: "SAP Center",
    },
    {
      id: "SEA",
      name: "시애틀 크라켄",
      nameEn: "Seattle Kraken",
      division: "퍼시픽",
      divisionEn: "Pacific",
      city: "시애틀",
      cityEn: "Seattle",
      stadium: "클라이밋 플레지 아레나",
      stadiumEn: "Climate Pledge Arena",
    },
    {
      id: "VAN",
      name: "밴쿠버 캐넉스",
      nameEn: "Vancouver Canucks",
      division: "퍼시픽",
      divisionEn: "Pacific",
      city: "밴쿠버",
      cityEn: "Vancouver",
      stadium: "로저스 아레나",
      stadiumEn: "Rogers Arena",
    },
    {
      id: "VGK",
      name: "베가스 골든 나이츠",
      nameEn: "Vegas Golden Knights",
      division: "퍼시픽",
      divisionEn: "Pacific",
      city: "라스베이거스",
      cityEn: "Las Vegas",
      stadium: "T-모바일 아레나",
      stadiumEn: "T-Mobile Arena",
    },
  ],
  "K-LEAGUE": [
    {
      id: "ULSAN_HD",
      name: "울산 HD",
      nameEn: "Ulsan HD FC",
      division: "K리그1",
      divisionEn: "K League 1",
      city: "울산",
      cityEn: "Ulsan",
      stadium: "울산문수축구경기장",
      stadiumEn: "Ulsan Munsu Stadium",
    },
    {
      id: "POHANG",
      name: "포항 스틸러스",
      nameEn: "Pohang Steelers",
      division: "K리그1",
      divisionEn: "K League 1",
      city: "경북 포항",
      cityEn: "Pohang",
      stadium: "포항스틸야드",
      stadiumEn: "Pohang Steelyard",
    },
    {
      id: "GANGWON",
      name: "강원 FC",
      nameEn: "Gangwon FC",
      division: "K리그1",
      divisionEn: "K League 1",
      city: "강원 (강릉/춘천)",
      cityEn: "Gangwon",
      stadium: "강릉종합운동장 / 춘천송암스포츠타운",
      stadiumEn: "Gangneung / Chuncheon",
    },
    {
      id: "GIMCHEON",
      name: "김천 상무",
      nameEn: "Gimcheon Sangmu",
      division: "K리그1",
      divisionEn: "K League 1",
      city: "경북 김천",
      cityEn: "Gimcheon",
      stadium: "김천종합운동장",
      stadiumEn: "Gimcheon Sports Complex",
    },
    {
      id: "FC_SEOUL",
      name: "FC 서울",
      nameEn: "FC Seoul",
      division: "K리그1",
      divisionEn: "K League 1",
      city: "서울",
      cityEn: "Seoul",
      stadium: "서울월드컵경기장",
      stadiumEn: "Seoul World Cup Stadium",
    },
    {
      id: "SUWON_FC",
      name: "수원 FC",
      nameEn: "Suwon FC",
      division: "K리그1",
      divisionEn: "K League 1",
      city: "경기 수원",
      cityEn: "Suwon",
      stadium: "수원종합운동장",
      stadiumEn: "Suwon Sports Complex",
    },
    {
      id: "JEJU",
      name: "제주 유나이티드",
      nameEn: "Jeju United",
      division: "K리그1",
      divisionEn: "K League 1",
      city: "제주",
      cityEn: "Jeju",
      stadium: "제주월드컵경기장",
      stadiumEn: "Jeju World Cup Stadium",
    },
    {
      id: "DAEJEON",
      name: "대전 하나 시티즌",
      nameEn: "Daejeon Hana Citizen",
      division: "K리그1",
      divisionEn: "K League 1",
      city: "대전",
      cityEn: "Daejeon",
      stadium: "대전월드컵경기장",
      stadiumEn: "Daejeon World Cup Stadium",
    },
    {
      id: "GWANGJU",
      name: "광주 FC",
      nameEn: "Gwangju FC",
      division: "K리그1",
      divisionEn: "K League 1",
      city: "광주",
      cityEn: "Gwangju",
      stadium: "광주축구전용구장",
      stadiumEn: "Gwangju Football Stadium",
    },
    {
      id: "JEONBUK",
      name: "전북 현대 모터스",
      nameEn: "Jeonbuk Hyundai Motors",
      division: "K리그1",
      divisionEn: "K League 1",
      city: "전북 전주",
      cityEn: "Jeonju",
      stadium: "전주월드컵경기장",
      stadiumEn: "Jeonju World Cup Stadium",
    },
    {
      id: "DAEGU",
      name: "대구 FC",
      nameEn: "Daegu FC",
      division: "K리그1",
      divisionEn: "K League 1",
      city: "대구",
      cityEn: "Daegu",
      stadium: "DGB대구은행파크",
      stadiumEn: "DGB Daegu Bank Park",
    },
    {
      id: "ANYANG",
      name: "FC 안양",
      nameEn: "FC Anyang",
      division: "K리그1",
      divisionEn: "K League 1",
      city: "경기 안양",
      cityEn: "Anyang",
      stadium: "안양종합운동장",
      stadiumEn: "Anyang Sports Complex",
    },
    {
      id: "INCHEON",
      name: "인천 유나이티드",
      nameEn: "Incheon United",
      division: "K리그2",
      divisionEn: "K League 2",
      city: "인천",
      cityEn: "Incheon",
      stadium: "인천축구전용경기장",
      stadiumEn: "Incheon Football Stadium",
    },
    {
      id: "SUWON_SAMSUNG",
      name: "수원 삼성 블루윙즈",
      nameEn: "Suwon Samsung Bluewings",
      division: "K리그2",
      divisionEn: "K League 2",
      city: "경기 수원",
      cityEn: "Suwon",
      stadium: "수원월드컵경기장",
      stadiumEn: "Suwon World Cup Stadium",
    },
    {
      id: "BUSAN",
      name: "부산 아이파크",
      nameEn: "Busan IPark",
      division: "K리그2",
      divisionEn: "K League 2",
      city: "부산",
      cityEn: "Busan",
      stadium: "부산아시아드주경기장",
      stadiumEn: "Busan Asiad Main Stadium",
    },
    {
      id: "SEOUL_ELAND",
      name: "서울 이랜드 FC",
      nameEn: "Seoul E-Land FC",
      division: "K리그2",
      divisionEn: "K League 2",
      city: "서울",
      cityEn: "Seoul",
      stadium: "목동종합운동장",
      stadiumEn: "Mokdong Stadium",
    },
    {
      id: "JEONNAM",
      name: "전남 드래곤즈",
      nameEn: "Jeonnam Dragons",
      division: "K리그2",
      divisionEn: "K League 2",
      city: "전남 광양",
      cityEn: "Gwangyang",
      stadium: "광양축구전용구장",
      stadiumEn: "Gwangyang Football Stadium",
    },
    {
      id: "GIMPO",
      name: "김포 FC",
      nameEn: "Gimpo FC",
      division: "K리그2",
      divisionEn: "K League 2",
      city: "경기 김포",
      cityEn: "Gimpo",
      stadium: "김포솔터축구장",
      stadiumEn: "Gimpo Solteo Football Field",
    },
    {
      id: "BUCHEON",
      name: "부천 FC 1995",
      nameEn: "Bucheon FC 1995",
      division: "K리그2",
      divisionEn: "K League 2",
      city: "경기 부천",
      cityEn: "Bucheon",
      stadium: "부천종합운동장",
      stadiumEn: "Bucheon Sports Complex",
    },
    {
      id: "ASAN",
      name: "충남 아산 FC",
      nameEn: "Chungnam Asan FC",
      division: "K리그2",
      divisionEn: "K League 2",
      city: "충남 아산",
      cityEn: "Asan",
      stadium: "이순신종합운동장",
      stadiumEn: "Yi Sun-sin Stadium",
    },
    {
      id: "CHEONGJU",
      name: "충북 청주 FC",
      nameEn: "Chungbuk Cheongju FC",
      division: "K리그2",
      divisionEn: "K League 2",
      city: "충북 청주",
      cityEn: "Cheongju",
      stadium: "청주종합경기장",
      stadiumEn: "Cheongju Sports Complex",
    },
    {
      id: "SEONGNAM",
      name: "성남 FC",
      nameEn: "Seongnam FC",
      division: "K리그2",
      divisionEn: "K League 2",
      city: "경기 성남",
      cityEn: "Seongnam",
      stadium: "탄천종합운동장",
      stadiumEn: "Tancheon Sports Complex",
    },
    {
      id: "GYEONGNAM",
      name: "경남 FC",
      nameEn: "Gyeongnam FC",
      division: "K리그2",
      divisionEn: "K League 2",
      city: "경남 창원",
      cityEn: "Changwon",
      stadium: "창원축구센터",
      stadiumEn: "Changwon Football Center",
    },
    {
      id: "ANSAN",
      name: "안산 그리너스",
      nameEn: "Ansan Greeners",
      division: "K리그2",
      divisionEn: "K League 2",
      city: "경기 안산",
      cityEn: "Ansan",
      stadium: "안산와~스타디움",
      stadiumEn: "Ansan Wa~ Stadium",
    },
    {
      id: "CHEONAN",
      name: "천안 시티 FC",
      nameEn: "Cheonan City FC",
      division: "K리그2",
      divisionEn: "K League 2",
      city: "충남 천안",
      cityEn: "Cheonan",
      stadium: "천안종합운동장",
      stadiumEn: "Cheonan Sports Complex",
    },
  ],
  NFL: [
    {
      id: "BUF",
      name: "버펄로 빌스",
      nameEn: "Buffalo Bills",
      division: "AFC 동부",
      divisionEn: "AFC East",
      city: "버펄로 (오처드파크)",
      cityEn: "Buffalo (Orchard Park)",
      stadium: "하이마크 스타디움",
      stadiumEn: "Highmark Stadium",
    },
    {
      id: "MIA",
      name: "마이애미 돌핀스",
      nameEn: "Miami Dolphins",
      division: "AFC 동부",
      divisionEn: "AFC East",
      city: "마이애미 (가든스)",
      cityEn: "Miami (Gardens)",
      stadium: "하드록 스타디움",
      stadiumEn: "Hard Rock Stadium",
    },
    {
      id: "NE",
      name: "뉴잉글랜드 패트리어츠",
      nameEn: "New England Patriots",
      division: "AFC 동부",
      divisionEn: "AFC East",
      city: "보스턴 (폭스버러)",
      cityEn: "Boston (Foxborough)",
      stadium: "질레트 스타디움",
      stadiumEn: "Gillette Stadium",
    },
    {
      id: "NYJ",
      name: "뉴욕 제츠",
      nameEn: "New York Jets",
      division: "AFC 동부",
      divisionEn: "AFC East",
      city: "뉴욕 (뉴저지)",
      cityEn: "New York (New Jersey)",
      stadium: "메트라이프 스타디움",
      stadiumEn: "MetLife Stadium",
    },
    {
      id: "BAL",
      name: "볼티모어 레이븐스",
      nameEn: "Baltimore Ravens",
      division: "AFC 북부",
      divisionEn: "AFC North",
      city: "볼티모어",
      cityEn: "Baltimore",
      stadium: "M&T 뱅크 스타디움",
      stadiumEn: "M&T Bank Stadium",
    },
    {
      id: "CIN",
      name: "신시내티 벵골스",
      nameEn: "Cincinnati Bengals",
      division: "AFC 북부",
      divisionEn: "AFC North",
      city: "신시내티",
      cityEn: "Cincinnati",
      stadium: "페이코 스타디움",
      stadiumEn: "Paycor Stadium",
    },
    {
      id: "CLE",
      name: "클리블랜드 브라운스",
      nameEn: "Cleveland Browns",
      division: "AFC 북부",
      divisionEn: "AFC North",
      city: "클리블랜드",
      cityEn: "Cleveland",
      stadium: "헌팅턴 뱅크 필드",
      stadiumEn: "Huntington Bank Field",
    },
    {
      id: "PIT",
      name: "피츠버그 스틸러스",
      nameEn: "Pittsburgh Steelers",
      division: "AFC 북부",
      divisionEn: "AFC North",
      city: "피츠버그",
      cityEn: "Pittsburgh",
      stadium: "아크리스어 스타디움",
      stadiumEn: "Acrisure Stadium",
    },
    {
      id: "HOU",
      name: "휴스턴 텍선스",
      nameEn: "Houston Texans",
      division: "AFC 남부",
      divisionEn: "AFC South",
      city: "휴스턴",
      cityEn: "Houston",
      stadium: "NRG 스타디움",
      stadiumEn: "NRG Stadium",
    },
    {
      id: "IND",
      name: "인디애나폴리스 콜츠",
      nameEn: "Indianapolis Colts",
      division: "AFC 남부",
      divisionEn: "AFC South",
      city: "인디애나폴리스",
      cityEn: "Indianapolis",
      stadium: "루카스 오일 스타디움",
      stadiumEn: "Lucas Oil Stadium",
    },
    {
      id: "JAX",
      name: "잭슨빌 재규어스",
      nameEn: "Jacksonville Jaguars",
      division: "AFC 남부",
      divisionEn: "AFC South",
      city: "잭슨빌",
      cityEn: "Jacksonville",
      stadium: "에버뱅크 스타디움",
      stadiumEn: "EverBank Stadium",
    },
    {
      id: "TEN",
      name: "테네시 타이탄스",
      nameEn: "Tennessee Titans",
      division: "AFC 남부",
      divisionEn: "AFC South",
      city: "내슈빌",
      cityEn: "Nashville",
      stadium: "닛산 스타디움",
      stadiumEn: "Nissan Stadium",
    },
    {
      id: "DEN",
      name: "덴버 브롱코스",
      nameEn: "Denver Broncos",
      division: "AFC 서부",
      divisionEn: "AFC West",
      city: "덴버",
      cityEn: "Denver",
      stadium: "임파워 필드 앳 마일 하이",
      stadiumEn: "Empower Field at Mile High",
    },
    {
      id: "KC",
      name: "캔자스시티 치프스",
      nameEn: "Kansas City Chiefs",
      division: "AFC 서부",
      divisionEn: "AFC West",
      city: "캔자스시티",
      cityEn: "Kansas City",
      stadium: "애로우헤드 스타디움",
      stadiumEn: "GEHA Field at Arrowhead",
    },
    {
      id: "LV",
      name: "라스베이거스 레이더스",
      nameEn: "Las Vegas Raiders",
      division: "AFC 서부",
      divisionEn: "AFC West",
      city: "라스베이거스",
      cityEn: "Las Vegas",
      stadium: "얼리전트 스타디움",
      stadiumEn: "Allegiant Stadium",
    },
    {
      id: "LAC",
      name: "LA 차저스",
      nameEn: "Los Angeles Chargers",
      division: "AFC 서부",
      divisionEn: "AFC West",
      city: "로스앤젤레스",
      cityEn: "Los Angeles",
      stadium: "소파이 스타디움",
      stadiumEn: "SoFi Stadium",
    },
    {
      id: "DAL",
      name: "댈러스 카우보이스",
      nameEn: "Dallas Cowboys",
      division: "NFC 동부",
      divisionEn: "NFC East",
      city: "댈러스 (알링턴)",
      cityEn: "Dallas (Arlington)",
      stadium: "AT&T 스타디움",
      stadiumEn: "AT&T Stadium",
    },
    {
      id: "NYG",
      name: "뉴욕 자이언츠",
      nameEn: "New York Giants",
      division: "NFC 동부",
      divisionEn: "NFC East",
      city: "뉴욕 (뉴저지)",
      cityEn: "New York (New Jersey)",
      stadium: "메트라이프 스타디움",
      stadiumEn: "MetLife Stadium",
    },
    {
      id: "PHI",
      name: "필라델피아 이글스",
      nameEn: "Philadelphia Eagles",
      division: "NFC 동부",
      divisionEn: "NFC East",
      city: "필라델피아",
      cityEn: "Philadelphia",
      stadium: "링컨 파이낸셜 필드",
      stadiumEn: "Lincoln Financial Field",
    },
    {
      id: "WAS",
      name: "워싱턴 커맨더스",
      nameEn: "Washington Commanders",
      division: "NFC 동부",
      divisionEn: "NFC East",
      city: "워싱턴 D.C. (랜드오버)",
      cityEn: "Washington D.C. (Landover)",
      stadium: "노스웨스트 스타디움",
      stadiumEn: "Northwest Stadium",
    },
    {
      id: "CHI",
      name: "시카고 베어스",
      nameEn: "Chicago Bears",
      division: "NFC 북부",
      divisionEn: "NFC North",
      city: "시카고",
      cityEn: "Chicago",
      stadium: "솔저 필드",
      stadiumEn: "Soldier Field",
    },
    {
      id: "DET",
      name: "디트로이트 라이온스",
      nameEn: "Detroit Lions",
      division: "NFC 북부",
      divisionEn: "NFC North",
      city: "디트로이트",
      cityEn: "Detroit",
      stadium: "포드 필드",
      stadiumEn: "Ford Field",
    },
    {
      id: "GB",
      name: "그린베이 패커스",
      nameEn: "Green Bay Packers",
      division: "NFC 북부",
      divisionEn: "NFC North",
      city: "그린베이",
      cityEn: "Green Bay",
      stadium: "램보 필드",
      stadiumEn: "Lambeau Field",
    },
    {
      id: "MIN",
      name: "미네소타 바이킹스",
      nameEn: "Minnesota Vikings",
      division: "NFC 북부",
      divisionEn: "NFC North",
      city: "미니애폴리스",
      cityEn: "Minneapolis",
      stadium: "U.S. 뱅크 스타디움",
      stadiumEn: "U.S. Bank Stadium",
    },
    {
      id: "ATL",
      name: "애틀랜타 팰컨스",
      nameEn: "Atlanta Falcons",
      division: "NFC 남부",
      divisionEn: "NFC South",
      city: "애틀랜타",
      cityEn: "Atlanta",
      stadium: "메르세데스-벤츠 스타디움",
      stadiumEn: "Mercedes-Benz Stadium",
    },
    {
      id: "CAR",
      name: "캐롤라이나 팬서스",
      nameEn: "Carolina Panthers",
      division: "NFC 남부",
      divisionEn: "NFC South",
      city: "샬럿",
      cityEn: "Charlotte",
      stadium: "뱅크 오브 아메리카 스타디움",
      stadiumEn: "Bank of America Stadium",
    },
    {
      id: "NO",
      name: "뉴올리언스 세인츠",
      nameEn: "New Orleans Saints",
      division: "NFC 남부",
      divisionEn: "NFC South",
      city: "뉴올리언스",
      cityEn: "New Orleans",
      stadium: "시저스 슈퍼돔",
      stadiumEn: "Caesars Superdome",
    },
    {
      id: "TB",
      name: "탬파베이 버커니어스",
      nameEn: "Tampa Bay Buccaneers",
      division: "NFC 남부",
      divisionEn: "NFC South",
      city: "탬파",
      cityEn: "Tampa",
      stadium: "레이먼드 제임스 스타디움",
      stadiumEn: "Raymond James Stadium",
    },
    {
      id: "ARI",
      name: "애리조나 카디널스",
      nameEn: "Arizona Cardinals",
      division: "NFC 서부",
      divisionEn: "NFC West",
      city: "피닉스 (글렌데일)",
      cityEn: "Phoenix (Glendale)",
      stadium: "스테이트 팜 스타디움",
      stadiumEn: "State Farm Stadium",
    },
    {
      id: "LAR",
      name: "LA 램스",
      nameEn: "Los Angeles Rams",
      division: "NFC 서부",
      divisionEn: "NFC West",
      city: "로스앤젤레스",
      cityEn: "Los Angeles",
      stadium: "소파이 스타디움",
      stadiumEn: "SoFi Stadium",
    },
    {
      id: "SF",
      name: "샌프란시스코 49ers",
      nameEn: "San Francisco 49ers",
      division: "NFC 서부",
      divisionEn: "NFC West",
      city: "샌프란시스코 (산타클라라)",
      cityEn: "San Francisco (Santa Clara)",
      stadium: "리바이스 스타디움",
      stadiumEn: "Levi's Stadium",
    },
    {
      id: "SEA",
      name: "시애틀 시호크스",
      nameEn: "Seattle Seahawks",
      division: "NFC 서부",
      divisionEn: "NFC West",
      city: "시애틀",
      cityEn: "Seattle",
      stadium: "루멘 필드",
      stadiumEn: "Lumen Field",
    },
  ],
  UCL: [
    {
      id: "MCI",
      name: "맨체스터 시티",
      nameEn: "Manchester City",
      division: "프리미어리그 (잉글랜드)",
      divisionEn: "Premier League",
      city: "맨체스터",
      cityEn: "Manchester",
      stadium: "에티하드 스타디움",
      stadiumEn: "Etihad Stadium",
    },
    {
      id: "ARS",
      name: "아스널",
      nameEn: "Arsenal",
      division: "프리미어리그 (잉글랜드)",
      divisionEn: "Premier League",
      city: "런던 (이즐링턴)",
      cityEn: "London (Islington)",
      stadium: "에미레이츠 스타디움",
      stadiumEn: "Emirates Stadium",
    },
    {
      id: "LIV",
      name: "리버풀",
      nameEn: "Liverpool",
      division: "프리미어리그 (잉글랜드)",
      divisionEn: "Premier League",
      city: "리버풀",
      cityEn: "Liverpool",
      stadium: "안필드",
      stadiumEn: "Anfield",
    },
    {
      id: "AVL",
      name: "아스톤 빌라",
      nameEn: "Aston Villa",
      division: "프리미어리그 (잉글랜드)",
      divisionEn: "Premier League",
      city: "버밍엄",
      cityEn: "Birmingham",
      stadium: "빌라 파크",
      stadiumEn: "Villa Park",
    },
    {
      id: "RMA",
      name: "레알 마드리드",
      nameEn: "Real Madrid",
      division: "라리가 (스페인)",
      divisionEn: "La Liga",
      city: "마드리드",
      cityEn: "Madrid",
      stadium: "산티아고 베르나베우",
      stadiumEn: "Santiago Bernabéu",
    },
    {
      id: "BAR",
      name: "바르셀로나",
      nameEn: "FC Barcelona",
      division: "라리가 (스페인)",
      divisionEn: "La Liga",
      city: "바르셀로나",
      cityEn: "Barcelona",
      stadium: "에스타디 올림픽",
      stadiumEn: "Estadi Olímpic",
    },
    {
      id: "GIR",
      name: "지로나",
      nameEn: "Girona FC",
      division: "라리가 (스페인)",
      divisionEn: "La Liga",
      city: "지로나",
      cityEn: "Girona",
      stadium: "몬틸리비",
      stadiumEn: "Montilivi",
    },
    {
      id: "ATM",
      name: "아틀레티코 마드리드",
      nameEn: "Atlético Madrid",
      division: "라리가 (스페인)",
      divisionEn: "La Liga",
      city: "마드리드",
      cityEn: "Madrid",
      stadium: "시비타스 메트로폴리타노",
      stadiumEn: "Cívitas Metropolitano",
    },
    {
      id: "B04",
      name: "바이어 레버쿠젠",
      nameEn: "Bayer Leverkusen",
      division: "분데스리가 (독일)",
      divisionEn: "Bundesliga",
      city: "레버쿠젠",
      cityEn: "Leverkusen",
      stadium: "바이아레나",
      stadiumEn: "BayArena",
    },
    {
      id: "VFB",
      name: "VfB 슈투트가르트",
      nameEn: "VfB Stuttgart",
      division: "분데스리가 (독일)",
      divisionEn: "Bundesliga",
      city: "슈투트가르트",
      cityEn: "Stuttgart",
      stadium: "MHP아레나",
      stadiumEn: "MHPArena",
    },
    {
      id: "FCB",
      name: "바이에른 뮌헨",
      nameEn: "Bayern Munich",
      division: "분데스리가 (독일)",
      divisionEn: "Bundesliga",
      city: "뮌헨",
      cityEn: "Munich",
      stadium: "알리안츠 아레나",
      stadiumEn: "Allianz Arena",
    },
    {
      id: "RBL",
      name: "RB 라이프치히",
      nameEn: "RB Leipzig",
      division: "분데스리가 (독일)",
      divisionEn: "Bundesliga",
      city: "라이프치히",
      cityEn: "Leipzig",
      stadium: "레드불 아레나",
      stadiumEn: "Red Bull Arena",
    },
    {
      id: "BVB",
      name: "보루시아 도르트문트",
      nameEn: "Borussia Dortmund",
      division: "분데스리가 (독일)",
      divisionEn: "Bundesliga",
      city: "도르트문트",
      cityEn: "Dortmund",
      stadium: "지그날 이두나 파크",
      stadiumEn: "Signal Iduna Park",
    },
    {
      id: "INT",
      name: "인터 밀란",
      nameEn: "Inter Milan",
      division: "세리에 A (이탈리아)",
      divisionEn: "Serie A",
      city: "밀라노",
      cityEn: "Milan",
      stadium: "산 시로",
      stadiumEn: "San Siro",
    },
    {
      id: "ACM",
      name: "AC 밀란",
      nameEn: "AC Milan",
      division: "세리에 A (이탈리아)",
      divisionEn: "Serie A",
      city: "밀라노",
      cityEn: "Milan",
      stadium: "산 시로",
      stadiumEn: "San Siro",
    },
    {
      id: "JUV",
      name: "유벤투스",
      nameEn: "Juventus",
      division: "세리에 A (이탈리아)",
      divisionEn: "Serie A",
      city: "토리노",
      cityEn: "Turin",
      stadium: "알리안츠 스타디움",
      stadiumEn: "Allianz Stadium",
    },
    {
      id: "ATA",
      name: "아탈란타",
      nameEn: "Atalanta",
      division: "세리에 A (이탈리아)",
      divisionEn: "Serie A",
      city: "베르가모",
      cityEn: "Bergamo",
      stadium: "게비스 스타디움",
      stadiumEn: "Gewiss Stadium",
    },
    {
      id: "BOL",
      name: "볼로냐",
      nameEn: "Bologna",
      division: "세리에 A (이탈리아)",
      divisionEn: "Serie A",
      city: "볼로냐",
      cityEn: "Bologna",
      stadium: "레나토 달라라",
      stadiumEn: "Renato Dall'Ara",
    },
    {
      id: "PSG",
      name: "파리 생제르맹",
      nameEn: "Paris Saint-Germain",
      division: "리그 1 (프랑스)",
      divisionEn: "Ligue 1",
      city: "파리",
      cityEn: "Paris",
      stadium: "파르크 데 프랭스",
      stadiumEn: "Parc des Princes",
    },
    {
      id: "MON",
      name: "AS 모나코",
      nameEn: "AS Monaco",
      division: "리그 1 (프랑스)",
      divisionEn: "Ligue 1",
      city: "모나코",
      cityEn: "Monaco",
      stadium: "루이 2세 스타디움",
      stadiumEn: "Stade Louis II",
    },
    {
      id: "BRE",
      name: "브레스트",
      nameEn: "Brest",
      division: "리그 1 (프랑스)",
      divisionEn: "Ligue 1",
      city: "브레스트",
      cityEn: "Brest",
      stadium: "스타드 드 루두루",
      stadiumEn: "Stade de Roudourou",
    },
    {
      id: "LIL",
      name: "릴",
      nameEn: "Lille OSC",
      division: "리그 1 (프랑스)",
      divisionEn: "Ligue 1",
      city: "릴",
      cityEn: "Lille",
      stadium: "피에르 모루아",
      stadiumEn: "Stade Pierre-Mauroy",
    },
    {
      id: "PSV",
      name: "PSV 에인트호번",
      nameEn: "PSV Eindhoven",
      division: "에레디비시 (네덜란드)",
      divisionEn: "Eredivisie",
      city: "에인트호번",
      cityEn: "Eindhoven",
      stadium: "필립스 스타디움",
      stadiumEn: "Philips Stadion",
    },
    {
      id: "FEY",
      name: "페예노르트",
      nameEn: "Feyenoord",
      division: "에레디비시 (네덜란드)",
      divisionEn: "Eredivisie",
      city: "로테르담",
      cityEn: "Rotterdam",
      stadium: "더 카위프",
      stadiumEn: "De Kuip",
    },
    {
      id: "SCP",
      name: "스포르팅 CP",
      nameEn: "Sporting CP",
      division: "프리메이라리가 (포르투갈)",
      divisionEn: "Primeira Liga",
      city: "리스본",
      cityEn: "Lisbon",
      stadium: "주제 알발라드",
      stadiumEn: "José Alvalade",
    },
    {
      id: "BEN",
      name: "벤피카",
      nameEn: "Benfica",
      division: "프리메이라리가 (포르투갈)",
      divisionEn: "Primeira Liga",
      city: "리스본",
      cityEn: "Lisbon",
      stadium: "다 루스",
      stadiumEn: "Estádio da Luz",
    },
    {
      id: "BRU",
      name: "클럽 브뤼헤",
      nameEn: "Club Brugge",
      division: "프로리그 (벨기에)",
      divisionEn: "Pro League",
      city: "브뤼헤",
      cityEn: "Bruges",
      stadium: "얀 브레이덜 스타디움",
      stadiumEn: "Jan Breydel Stadium",
    },
    {
      id: "CEL",
      name: "셀틱",
      nameEn: "Celtic",
      division: "프리미어십 (스코틀랜드)",
      divisionEn: "Premiership",
      city: "글래스고",
      cityEn: "Glasgow",
      stadium: "셀틱 파크",
      stadiumEn: "Celtic Park",
    },
    {
      id: "STU",
      name: "슈투름 그라츠",
      nameEn: "Sturm Graz",
      division: "분데스리가 (오스트리아)",
      divisionEn: "Bundesliga",
      city: "그라츠",
      cityEn: "Graz",
      stadium: "메르쿠어 아레나",
      stadiumEn: "Merkur Arena",
    },
    {
      id: "RBS",
      name: "레드불 잘츠부르크",
      nameEn: "Red Bull Salzburg",
      division: "분데스리가 (오스트리아)",
      divisionEn: "Bundesliga",
      city: "잘츠부르크",
      cityEn: "Salzburg",
      stadium: "레드불 아레나",
      stadiumEn: "Red Bull Arena",
    },
    {
      id: "YB",
      name: "영 보이스",
      nameEn: "Young Boys",
      division: "슈퍼리그 (스위스)",
      divisionEn: "Super League",
      city: "베른",
      cityEn: "Bern",
      stadium: "방크도르프",
      stadiumEn: "Wankdorf",
    },
    {
      id: "SPP",
      name: "스파르타 프라하",
      nameEn: "Sparta Prague",
      division: "1. 체스카 (체코)",
      divisionEn: "First League",
      city: "프라하",
      cityEn: "Prague",
      stadium: "에펫 아레나",
      stadiumEn: "epet ARENA",
    },
    {
      id: "SLO",
      name: "슬로반 브라티슬라바",
      nameEn: "Slovan Bratislava",
      division: "수페르리가 (슬로바키아)",
      divisionEn: "Super Liga",
      city: "브라티슬라바",
      cityEn: "Bratislava",
      stadium: "테헬네 폴레",
      stadiumEn: "Tehelné pole",
    },
    {
      id: "SHA",
      name: "샤흐타르 도네츠크",
      nameEn: "Shakhtar Donetsk",
      division: "프리미어리그 (우크라이나)",
      divisionEn: "Premier League",
      city: "도네츠크",
      cityEn: "Donetsk",
      stadium: "펠틴스 아레나",
      stadiumEn: "Veltins-Arena",
    },
    {
      id: "DIN",
      name: "디나모 자그레브",
      nameEn: "Dinamo Zagreb",
      division: "HNL (크로아티아)",
      divisionEn: "HNL",
      city: "자그레브",
      cityEn: "Zagreb",
      stadium: "막시미르",
      stadiumEn: "Maksimir",
    },
    {
      id: "RSB",
      name: "츠르베나 즈베즈다",
      nameEn: "Red Star Belgrade",
      division: "수페르리가 (세르비아)",
      divisionEn: "SuperLiga",
      city: "베오그라드",
      cityEn: "Belgrade",
      stadium: "라이코 미티치",
      stadiumEn: "Rajko Mitić",
    },
  ],
};
